services:

  # postgres:
  #   image: postgres:16-alpine
  #   container_name: financial-records-postgres
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_DB=financial_records
  #     - POSTGRES_USER=financial_user
  #     - POSTGRES_PASSWORD=financial_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  waha:
    image: devlikeapro/waha:latest
    container_name: financial-waha
    platform: linux/amd64
    environment:
      WHATSAPP_HOOK_URL: http://host.docker.internal:5678/webhook/webhook
      WHATSAPP_DEFAULT_ENGINE: GOWS
      WHATSAPP_HOOK_EVENTS: message
      WAHA_NO_API_KEY: true
      WAHA_DASHBOARD_NO_PASSWORD: true
      WHATSAPP_SWAGGER_NO_PASSWORD: true

    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "3000:3000"

  n8n:
    image: n8nio/n8n:latest
    container_name: financial-n8n
    platform: linux/amd64
    environment:
      WEBHOOK_URL: http://host.docker.internal:5678
      N8N_HOST: host.docker.internal
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"

volumes:
  postgres-data:
  waha_sessions:
  waha_media:
  n8n_data: